### ISSUE TITLE
Flow error when uploading new file

### ISSUE THREAD

**Issue by frisbeeErick** [DouglasCAyers/salesforce-chatter-bot-files#1]
When uploading a brand new file in the Files tab, the following exception occurs.  After researching the issue, I've found that the error happens when there are no followers on a file.  The flow variable varEmailAddresses can't be set to a blank value.  The invocable apex creates a response for each request and assigns a list of emails to the res.emailAddresses variable.  When there are no followers for a file, that list is blank and the flow errors.

	
Error: There were custom validation error(s) encountered while saving the affected record(s). The first validation error encountered was "Apex trigger ChatterBotFileVersionTrigger caused an unexpected exception, contact your administrator: ChatterBotFileVersionTrigger: execution of AfterInsert caused by: System.DmlException: Upsert failed. First exception on row 0; first error: CANNOT_EXECUTE_FLOW_TRIGGER, The record couldn’t be saved because it failed to trigger a flow. A flow trigger failed to execute the flow with version ID 3016C0000000D9l. Flow error messages: <b>An unhandled fault has occurred in this flow</b><br>An unhandled fault has occurred while processing the flow. Please contact your system administrator for more information. Contact your administrator for help.: []: Class.ChatterBotFileVersionTriggerHandler.createChatterBotFiles: line 28, column 1".

**Comment by douglascayers** [comment]
Thanks @frisbeeErick for the report and details. I'll get that fixed. One of the many perils of late night coding, missing the most obvious use case!
