### ISSUE TITLE
AutoCreateChatterBotFiles does not fire on first insert

### ISSUE THREAD

**Issue by wadams2010** [DouglasCAyers/salesforce-chatter-bot-files#3]
When I first upload a file through chatter with the autoCreateChatterBotFiles set as TRUE the flow does not create a Chatter Bot File record. However, when I update the version of the file by updating the file it will create the Chatter Bot File record. Is there a way we can get the app to create the Chatter Bot File the first time a file is uploaded through Chatter? Let me know if I am missing something on my end. Thanks Doug!

**Comment by douglascayers** [comment]
Hi @wadams2010,

I am not able to reproduce this. Can you double-check that the Custom Setting **Chatter Bot Files Setting** has a default organization value checked for **Auto Create Chatter Bot File Records?**

![image](https://cloud.githubusercontent.com/assets/4142577/24982182/b7d7aa18-1fa5-11e7-97d7-9e5fe8edda62.png)

In my dev org, as the System Administrator, I enabled that custom setting above then uploaded a new Chatter File from the **Files"** tab. I then navigated to the **Chatter Bot Files** tab and saw the new record created for the file having been inserted.

Could you provide screen shots or a quick video of your setup and test steps?

Perhaps try re-installing the solution from GitHub?

Thanks,

Doug

**Comment by douglascayers** [comment]
Closing old issues, if this is still a problem for you please comment and I'll re-open. Thanks!
