### ISSUE TITLE
Flow error when adding new file version

### ISSUE THREAD

**Issue by frisbeeErick** [DouglasCAyers/salesforce-chatter-bot-files#4]
Steps to recreate:
1. Upload new file
2. Upload new file version for that file
3. Log in as a different user with access to the file
4. Upload new file version for that file

This throws the following error:
Apex script unhandled trigger exception by user/organization: ******** Source organization: ********(null)
ChatterBotFileVersionTrigger: execution of AfterInsert

caused by: System.DmlException: Upsert failed. First exception on row 0 with id *******; first error: CANNOT_EXECUTE_FLOW_TRIGGER, The record couldn’t be saved because it failed to trigger a flow. A flow trigger failed to execute the flow with version ID *******. Flow error messages: <b>An unhandled fault has occurred in this flow</b><br>An unhandled fault has occurred while processing the flow.  Please contact your system administrator for more information.  Contact your administrator for help.: []

Class.ChatterBotFileVersionTriggerHandler.createChatterBotFiles: line 97, column 1
Trigger.ChatterBotFileVersionTrigger: line 3, column 1

**Comment by frisbeeErick** [comment]
I resolved this problem by creating a sharing rule for Chatter Bot Files.  As long as the user has access to the Chatter Bot File they can upload a new version of the file.

**Comment by douglascayers** [comment]
Hi @frisbeeErick,

Sorry for delay, was out of town all last week and just now catching up on emails.

Glad you figured it out the issue.

Hrmm... I thought this would have been mitigated by the `ChatterBotFileVersionTriggerHandler` being declared **without sharing**. Can you confirm if your copy of `ChatterBotFileVersionTriggerHandler` is declared as: **public without sharing ChatterBotFileVersionTriggerHandler** or not?

Thanks,

Doug

**Comment by frisbeeErick** [comment]
Doug,

You are correct about the class being "without sharing."  The sharing rule fixed the error in UATEXT, but our user tried to upload again in prod and still received the following error.  However, I have no issue uploading a new version as a System Admin.

Error: There were custom validation error(s) encountered while saving the affected record(s). The first validation error encountered was "Apex trigger ChatterBotFileVersionTrigger caused an unexpected exception, contact your administrator: ChatterBotFileVersionTrigger: execution of AfterInsert caused by: System.DmlException: Upsert failed. First exception on row 0 with id a6yC00000008S34IAE; first error: CANNOT_EXECUTE_FLOW_TRIGGER, The record couldn’t be saved because it failed to trigger a flow. A flow trigger failed to execute the flow with version ID 301C00000000MOO. Flow error messages: <b>An unhandled fault has occurred in this flow</b><br>An unhandled fault has occurred while processing the flow. Please contact your system administrator for more information. Contact your administrator for help.: []: Class.ChatterBotFileVersionTriggerHandler.createChatterBotFiles: line 97, column 1".

**Comment by douglascayers** [comment]
To confirm, when the same user uploads a file in your sandbox it works as expected but in production it doesn't? If so then I recommend double checking all permissions and sharing rule settings between the two instances.

That appears to be a flow error email, was there another email with any more details about the problem?

**Comment by douglascayers** [comment]
Closing old issues, if this is still a problem for you please comment and I'll re-open. Thanks!
