### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [DouglasCAyers/salesforce-chatter-bot-files#5]
Hello Douglas,

Tried to deplyo but got below end result failure. Can you please advise?

Deployment Started
Status: Queued 
Status: InProgress 
Status: InProgress 
Status: InProgress 
Status: InProgress 
Status: InProgress 
Status: InProgress 
Status: InProgress 
Status: Completed 
Deployment CompleteTest failure, method: ChatterBotFileSendEmailInvocableTest.test_send_email -- System.EmailException: SendEmail failed. First exception on row 0; first error: INVALID_SAVE_AS_ACTIVITY_FLAG, saveAsActivity must be false when sending mail to users.: [saveAsActivity, true] stack Class.ChatterBotFileSendEmailInvocable.execute: line 75, column 1
Class.ChatterBotFileSendEmailInvocableTest.test_send_email: line 48, column 1

Kind regards,
Mario

**Comment by douglascayers** [comment]
Hi Mario,

Thanks for taking interest in my app! Could you confirm which kind of org (sandbox, production, developer) and which release (winter 18 or spring 18) you are trying to deploy to?

Thanks

**Comment by MarioVanDenEijnde** [comment]
Hello Doug,

Thanks for the quick reply.
I tested production and I think it is Winter 18 but not sure where I can read this.

If there is another way to deploy (eclips for example) please advise.

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
Hello Doug,

I just deployed in the sandbox and that seemed to work fine. Still testing this.

Kind regards,
Mario

From: Mario DeLaFini
Sent: Friday, 9 February 2018 21:49
To: 'DouglasCAyers/salesforce-chatter-bot-files' <reply@reply.github.com>; DouglasCAyers/salesforce-chatter-bot-files <salesforce-chatter-bot-files@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [DouglasCAyers/salesforce-chatter-bot-files] Deployment failed (#5)

Hello Doug,

Thanks for the quick reply.
I tested production and I think it is Winter 18 but not sure where I can read this.

If there is another way to deploy (eclips for example) please advise.

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
Hello Douglas,

Just so I understand.
When I upload a File in the Files section should there be a “Chatter Bot Files” record created? It doesn’t.
And if this is not the case which action should do this?

Kind regards,
Mario

From: Mario DeLaFini
Sent: Friday, 9 February 2018 21:59
To: 'DouglasCAyers/salesforce-chatter-bot-files' <reply@reply.github.com>; 'DouglasCAyers/salesforce-chatter-bot-files' <salesforce-chatter-bot-files@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [DouglasCAyers/salesforce-chatter-bot-files] Deployment failed (#5)

Hello Doug,

I just deployed in the sandbox and that seemed to work fine. Still testing this.

Kind regards,
Mario

From: Mario DeLaFini
Sent: Friday, 9 February 2018 21:49
To: 'DouglasCAyers/salesforce-chatter-bot-files' <reply@reply.github.com>; DouglasCAyers/salesforce-chatter-bot-files <salesforce-chatter-bot-files@noreply.github.com<mailto:salesforce-chatter-bot-files@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [DouglasCAyers/salesforce-chatter-bot-files] Deployment failed (#5)

Hello Doug,

Thanks for the quick reply.
I tested production and I think it is Winter 18 but not sure where I can read this.

If there is another way to deploy (eclips for example) please advise.

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
Hello Douglas,

Got it:
[cid:image002.jpg@01D3A1FE.C0E67450]

Kind regards,
Mario


From: Mario DeLaFini
Sent: Friday, 9 February 2018 22:28
To: 'DouglasCAyers/salesforce-chatter-bot-files' <reply@reply.github.com>; 'DouglasCAyers/salesforce-chatter-bot-files' <salesforce-chatter-bot-files@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [DouglasCAyers/salesforce-chatter-bot-files] Deployment failed (#5)

Hello Douglas,

Just so I understand.
When I upload a File in the Files section should there be a “Chatter Bot Files” record created? It doesn’t.
And if this is not the case which action should do this?

Kind regards,
Mario

From: Mario DeLaFini
Sent: Friday, 9 February 2018 21:59
To: 'DouglasCAyers/salesforce-chatter-bot-files' <reply@reply.github.com>; 'DouglasCAyers/salesforce-chatter-bot-files' <salesforce-chatter-bot-files@noreply.github.com<mailto:salesforce-chatter-bot-files@noreply.github.com>>
Cc: 'Author' <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [DouglasCAyers/salesforce-chatter-bot-files] Deployment failed (#5)

Hello Doug,

I just deployed in the sandbox and that seemed to work fine. Still testing this.

Kind regards,
Mario

From: Mario DeLaFini
Sent: Friday, 9 February 2018 21:49
To: 'DouglasCAyers/salesforce-chatter-bot-files' <reply@reply.github.com>; DouglasCAyers/salesforce-chatter-bot-files <salesforce-chatter-bot-files@noreply.github.com<mailto:salesforce-chatter-bot-files@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [DouglasCAyers/salesforce-chatter-bot-files] Deployment failed (#5)

Hello Doug,

Thanks for the quick reply.
I tested production and I think it is Winter 18 but not sure where I can read this.

If there is another way to deploy (eclips for example) please advise.

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
Hello Douglas,

I try to deploy from sandbox to production but do not succeed. (Uploaded an outbound package and try to deploy the inbound but only get errors)
Can you help me get it in production?

Just to inform you about our eventual goal:
We are looking for a way to synchronize files from sharepoint into a salesforce Library with a folder structure.
We manage with use of a datasync tool (simego) to get documents into the contentversion but only in a flat structure.
So we were looking for a way to add an “contentFolderMember” record to the appropriate folder in order to show the File in the folder.
That is when we got attention for your solution where we can use a process trigger to “read” for example the Files “TagCsv” info to find the folderName and add the record in a flow.
If you can advise another routine please suggest.

Thanks in advance.

Kind regards,
Mario

From: Mario DeLaFini
Sent: Friday, 9 February 2018 23:36
To: 'DouglasCAyers/salesforce-chatter-bot-files' <reply@reply.github.com>; 'DouglasCAyers/salesforce-chatter-bot-files' <salesforce-chatter-bot-files@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [DouglasCAyers/salesforce-chatter-bot-files] Deployment failed (#5)

Hello Douglas,

Got it:
[cid:image001.jpg@01D3A200.82EDF950]

Kind regards,
Mario


From: Mario DeLaFini
Sent: Friday, 9 February 2018 22:28
To: 'DouglasCAyers/salesforce-chatter-bot-files' <reply@reply.github.com>; 'DouglasCAyers/salesforce-chatter-bot-files' <salesforce-chatter-bot-files@noreply.github.com<mailto:salesforce-chatter-bot-files@noreply.github.com>>
Cc: 'Author' <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [DouglasCAyers/salesforce-chatter-bot-files] Deployment failed (#5)

Hello Douglas,

Just so I understand.
When I upload a File in the Files section should there be a “Chatter Bot Files” record created? It doesn’t.
And if this is not the case which action should do this?

Kind regards,
Mario

From: Mario DeLaFini
Sent: Friday, 9 February 2018 21:59
To: 'DouglasCAyers/salesforce-chatter-bot-files' <reply@reply.github.com>; 'DouglasCAyers/salesforce-chatter-bot-files' <salesforce-chatter-bot-files@noreply.github.com<mailto:salesforce-chatter-bot-files@noreply.github.com>>
Cc: 'Author' <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [DouglasCAyers/salesforce-chatter-bot-files] Deployment failed (#5)

Hello Doug,

I just deployed in the sandbox and that seemed to work fine. Still testing this.

Kind regards,
Mario

From: Mario DeLaFini
Sent: Friday, 9 February 2018 21:49
To: 'DouglasCAyers/salesforce-chatter-bot-files' <reply@reply.github.com>; DouglasCAyers/salesforce-chatter-bot-files <salesforce-chatter-bot-files@noreply.github.com<mailto:salesforce-chatter-bot-files@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [DouglasCAyers/salesforce-chatter-bot-files] Deployment failed (#5)

Hello Doug,

Thanks for the quick reply.
I tested production and I think it is Winter 18 but not sure where I can read this.

If there is another way to deploy (eclips for example) please advise.

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
Hello Douglas,

I have added “message.saveAsActivity = false;” to the class file “ChatterBotFileSendEmailInvocable”
And then I could deploy the solution fine.

Kind regards,
Mario

From: Mario DeLaFini
Sent: Saturday, 10 February 2018 00:19
To: 'DouglasCAyers/salesforce-chatter-bot-files' <reply@reply.github.com>; 'DouglasCAyers/salesforce-chatter-bot-files' <salesforce-chatter-bot-files@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [DouglasCAyers/salesforce-chatter-bot-files] Deployment failed (#5)

Hello Douglas,

I try to deploy from sandbox to production but do not succeed. (Uploaded an outbound package and try to deploy the inbound but only get errors)
Can you help me get it in production?

Just to inform you about our eventual goal:
We are looking for a way to synchronize files from sharepoint into a salesforce Library with a folder structure.
We manage with use of a datasync tool (simego) to get documents into the contentversion but only in a flat structure.
So we were looking for a way to add an “contentFolderMember” record to the appropriate folder in order to show the File in the folder.
That is when we got attention for your solution where we can use a process trigger to “read” for example the Files “TagCsv” info to find the folderName and add the record in a flow.
If you can advise another routine please suggest.

Thanks in advance.

Kind regards,
Mario

From: Mario DeLaFini
Sent: Friday, 9 February 2018 23:36
To: 'DouglasCAyers/salesforce-chatter-bot-files' <reply@reply.github.com>; 'DouglasCAyers/salesforce-chatter-bot-files' <salesforce-chatter-bot-files@noreply.github.com<mailto:salesforce-chatter-bot-files@noreply.github.com>>
Cc: 'Author' <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [DouglasCAyers/salesforce-chatter-bot-files] Deployment failed (#5)

Hello Douglas,

Got it:
[cid:image001.jpg@01D3A20D.A8EE9940]

Kind regards,
Mario


From: Mario DeLaFini
Sent: Friday, 9 February 2018 22:28
To: 'DouglasCAyers/salesforce-chatter-bot-files' <reply@reply.github.com>; 'DouglasCAyers/salesforce-chatter-bot-files' <salesforce-chatter-bot-files@noreply.github.com<mailto:salesforce-chatter-bot-files@noreply.github.com>>
Cc: 'Author' <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [DouglasCAyers/salesforce-chatter-bot-files] Deployment failed (#5)

Hello Douglas,

Just so I understand.
When I upload a File in the Files section should there be a “Chatter Bot Files” record created? It doesn’t.
And if this is not the case which action should do this?

Kind regards,
Mario

From: Mario DeLaFini
Sent: Friday, 9 February 2018 21:59
To: 'DouglasCAyers/salesforce-chatter-bot-files' <reply@reply.github.com>; 'DouglasCAyers/salesforce-chatter-bot-files' <salesforce-chatter-bot-files@noreply.github.com<mailto:salesforce-chatter-bot-files@noreply.github.com>>
Cc: 'Author' <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [DouglasCAyers/salesforce-chatter-bot-files] Deployment failed (#5)

Hello Doug,

I just deployed in the sandbox and that seemed to work fine. Still testing this.

Kind regards,
Mario

From: Mario DeLaFini
Sent: Friday, 9 February 2018 21:49
To: 'DouglasCAyers/salesforce-chatter-bot-files' <reply@reply.github.com>; DouglasCAyers/salesforce-chatter-bot-files <salesforce-chatter-bot-files@noreply.github.com<mailto:salesforce-chatter-bot-files@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [DouglasCAyers/salesforce-chatter-bot-files] Deployment failed (#5)

Hello Doug,

Thanks for the quick reply.
I tested production and I think it is Winter 18 but not sure where I can read this.

If there is another way to deploy (eclips for example) please advise.

Kind regards,
Mario

**Comment by douglascayers** [comment]
Hi @MarioVanDenEijnde,

Thanks for the updates. Sounds like you were able to get the app installed and all is good, I'll go ahead and close this issue.

That's a neat use case. I think your plan should work fine. Process Builder monitor the Chatter Bot File object and then launch a Flow to do what you need.

To automate the creation of **Chatter Bot Files** records, there is a custom setting `Chatter Bot Files Setting` with a single checkbox property. Check `Auto Create Chatter Bot File Records?` and that will create the custom object record any time a user creates a File (ContentVersion record). With that custom setting unchecked then it's up to the admin to cherry-pick which files they want to be monitored.

Hope it all works out for your use case!

Thanks
